platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
# ignore all warnings from all pods
inhibit_all_warnings!

def public_pods
  pod 'RxSwift', '4.1.2'
  pod 'RxCocoa', '4.1.2'
  pod 'Moya/RxSwift', '11.0.0'
  pod 'SwiftyJSON'
  pod 'Action', '3.5.0'
  pod 'Kingfisher'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Locksmith'
  pod 'SlideMenuControllerSwift'
end


def test_pods
  pod 'RxTest' 
  pod 'RxBlocking'
end	


abstract_target 'App' do
  # Public Pods
  public_pods

  # Targets
  target 'OKFitness' do
    use_frameworks!
  end

end
